### ISSUE TITLE
Warning on default completion page

### ISSUE THREAD

**Issue by t-schroeder** [mebis-lp/mod_learningmap#110] opened 2024-09-27 14:52 UTC
In Moodle 4.3+ there is a page called "default activity completion". It displays this with debug logging turned on:

```
Custom completion rule completiontype of module learningmap has wrong suffix and has been removed from the form. This has to be fixed by the developer
line 131 of /completion/classes/edit_base_form.php: call to debugging()
line 153 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion()
line 178 of /completion/classes/form/form_trait.php: call to core_completion_edit_base_form->add_completion_rules()
line 254 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_completion_elements()
line 102 of /completion/classes/defaultedit_form.php: call to core_completion_edit_base_form->definition()
line 217 of /lib/formslib.php: call to core_completion_defaultedit_form->definition()
line 47 of /completion/classes/defaultedit_form.php: call to moodleform->__construct()
line 83 of /course/classes/output/bulk_activity_completion_renderer.php: call to core_completion_defaultedit_form->__construct()
line 97 of /course/defaultcompletion.php: call to core_course_bulk_activity_completion_renderer->defaultcompletion()
```

**Comment by sh-csg** [comment] 2024-11-02 07:05
Thanks a lot for reporting this! Unfortunately I can't reproduce it. Do you use the current version of mod_learningmap?

**Comment by sh-csg** [comment] 2024-12-16 08:31
As the issue cannot be reproduced with the current version, I'll close it. Feel free to reopen it if you can provide any additional information!

**Closed by sh-csg** 2024-12-16 08:31 UTC
