### ISSUE TITLE
Adding a nested learningmap activity creates strange characters

### ISSUE THREAD

**Issue by billegs** [mebis-lp/mod_learningmap#100] opened 2024-04-29 08:13 UTC
1-Create a learning map activity 1
2-Create another learningmap activity 2
3- Edit learning map **1** and add activity **2**

Visit activity 2 - it shows up strange characters in (div activity description- no-overflow ) 
![learningmap-bug](https://github.com/mebis-lp/mod_learningmap/assets/98683002/18ef042d-365b-4845-90e4-cf2628c398fc)

**Comment by sh-csg** [comment] 2024-04-29 09:23
Thanks a lot for reporting this issue. Unfortunately I'm not able to reproduce it.
Could you please provide
* the version of mod_learningmap you are using
* the names of the activities?

**Comment by billegs** [comment] 2024-04-29 13:03
I am using the v0.9.7 with moodle 4.3. I have just upgraded to 4.4 the problem remains.
I have no specific activity, this happens in sub learningmap activity in learning map. But I have just found out it is the backlink which is causing the problem. When I disable it in the settings the problem goes away. I tested it with Boost and classic, it is the same...

In the console

**Comment by billegs** [comment] 2024-04-30 21:45
Now I have tested on 3 different server platforms and it is giving me the same error no matter what theme I am using. May be I wasn't clear enough which I've just realized. Iam using modle 4.4 without any plugins except Learningmap on php 8.1 environmnent

1-Create a learningmap activity **1** ( 
Show map on course page **✓**
Show backlinks on course module pages**✓**

2-Create another learningmap activity 2
Show map on course page **X**
Show backlinks on course module pages**✓**

3- Edit **learningmap activity 1** and add  **learningmap activity 2**
4-Save. and now We got a link to **activity 2** on the learning map **1**
5- Click on Activity 2. It is giving me error.

If you check the option 'Show map on course page'' on both activities, NO ERROR occurs.

**Comment by sh-csg** [comment] 2024-07-11 18:43
Will be fixed by #103

**Comment by billegs** [comment] 2024-07-14 21:28
Thank you, it works perfect now!

**Closed** 2024-07-17 15:16 UTC
